server:
  port: 8083
spring:
  application:
    name: cart-service
  datasource:
    url: 
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: 
    password: 
  cloud:
    nacos:
      server-addr: # nacos地址
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
