server:
  port: 8081
spring:
  application:
    name: user-login
  datasource:
    url: 
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: 
    password: 
  cloud:
    nacos:
      server-addr:  # nacos地址

