server:
  port: 8081
spring:
  application:
    name: user-login
  datasource:
    url: jdbc:mysql://47.112.106.211:10336/suyu-shopping?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123
  cloud:
    nacos:
      server-addr: 47.112.106.211:8848 # nacos地址

