server:
  port: 8082
spring:
  application:
    name: product-list
  datasource:
    url: jdbc:mysql://47.112.106.211:10336/suyu-product?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123
  cloud:
    nacos:
      server-addr: 47.112.106.211:8848 # nacos地址
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
